# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: true
  # Set the formatter to 'html'
  formatter: html
  # Output file instead of logging results
  output-file: 'resources/sass/linters/sass-lint.html'
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'resources/sass/**/*.s+(a|c)ss'
  ignore: 'node_modules/**/*.*'
# Rule Configuration
rules:
  nesting-depth:
  - 2
  -
    max-depth: 3
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 0
    -
      exclude:
        - breakpoint
        - mq
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 0
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
  variable-for-property:
    - 2
